LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := libjingle

LOCAL_CPPFLAGS := -DHAMMER_TIME=1 -DLOGGING=1 -DFEATURE_ENABLE_SSL -DFEATURE_ENABLE_VOICEMAIL -DFEATURE_ENABLE_PSTN -DHAVE_SRTP -DHASHNAMESPACE=__gnu_cxx -DHASH_NAMESPACE=__gnu_cxx -DPOSIX -DDISABLE_DYNAMIC_CAST -DHAVE_OPENSSL_SSL_H=1 -D_REENTRANT -DOS_LINUX=OS_LINUX -DLINUX -D_DEBUG -DFEATURE_ENABLE_VOICEMAIL -DEXPAT_RELATIVE_PATH -DSRTP_RELATIVE_PATH -DXML_STATIC -DANDROID

LOCAL_C_INCLUDES :=  $(LOCAL_PATH)/code/p2p/base $(LOCAL_PATH)/code/p2p/client $(LOCAL_PATH)/code/base $(LOCAL_PATH)/code/session/phone $(LOCAL_PATH)/code/session/tunnel $(LOCAL_PATH)/code/sound $(LOCAL_PATH)/code/xmllite $(LOCAL_PATH)/code/xmpp  

include $(BUILD_SHARED_LIBRARY)